import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {build} from 'esbuild';
import {chromium} from 'playwright';

test('browser menu, device dimensions, screenshot modal and narrow keyboard flow',async t=>{
  const {outputFiles}=await build({bundle:true,write:false,format:'iife',platform:'browser',define:{'process.env.NODE_ENV':'"production"'},stdin:{resolveDir:process.cwd(),loader:'jsx',contents:`
    import React,{useState} from 'react';import {createRoot} from 'react-dom/client';import {BrowserTools} from '#opencu/src/client/browser-tools.jsx';
    window.calls=[];window.updates=0;
    function Harness(){const[target,setTarget]=useState({id:'tab',kind:'tab'}),[size,setSize]=useState({width:1280,height:720}),[state,setState]=useState({enabled:true,controlEpoch:0}),[previewScale,setPreviewScale]=useState('1');
      window.switchTab=()=>setTarget({id:'other',kind:'tab'});
      const api=async(op,id,input)=>{window.calls.push({op,...input});if(op==='view-screenshot')return {mediaType:'image/png',data:'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aNXsAAAAASUVORK5CYII='};if(op==='view-find')return {...state,controlEpoch:state.controlEpoch+1,find:{query:input.query,found:input.query!=='missing',wrapped:input.backward===true}};setSize(input.size??{width:1280,height:720});return {...state,controlEpoch:state.controlEpoch+1,viewViewport:{overridden:input.size!==null}};};
      return <div className="tx-cu-pane" style={{width:320}}><div className="tx-cu-browser-navigation"><span>浏览器</span><BrowserTools sessionId="test" target={target} frame={{tabId:'tab',actor:'observer',...size}} state={state} api={api} onState={next=>{window.updates++;setState(next);}} onError={message=>window.error=message} previewScale={previewScale} onPreviewScale={setPreviewScale}/></div></div>;
    }createRoot(document.getElementById('root')).render(<Harness/>);
  `}});
  const browser=await chromium.launch({headless:true});t.after(()=>browser.close());const page=await browser.newPage({viewport:{width:320,height:650}});
  await page.route('http://localhost/browser-tools',route=>route.fulfill({contentType:'text/html',body:'<style>body{margin:0}</style><div id="root"></div>'}));await page.goto('http://localhost/browser-tools');
  await page.addStyleTag({content:await readFile(new URL(import.meta.resolve('#opencu/src/client/computer-use.css')),'utf8')});await page.addScriptTag({content:outputFiles[0].text});
  const options=page.getByRole('button',{name:'浏览器选项'});
  await options.click();await page.getByRole('menuitem',{name:'显示设备工具栏'}).press('Escape');assert.equal(await options.evaluate(el=>el===document.activeElement),true);
  await options.click();await page.getByRole('menuitem',{name:'显示设备工具栏'}).click();await page.getByRole('form',{name:'设备工具栏'}).waitFor();
  const zoom=page.getByLabel('设备预览缩放');await zoom.selectOption('fit');assert.equal(await zoom.inputValue(),'fit');await zoom.selectOption('0.5');assert.equal(await zoom.inputValue(),'0.5');assert.equal(await page.evaluate(()=>window.calls.length),0,'preview zoom is local, with no backend control writes');
  await page.getByRole('button',{name:'关闭设备工具栏'}).click();assert.equal(await page.evaluate(()=>window.calls.length),0,'showing and hiding controls does not take control');
  await options.click();await page.getByRole('menuitem',{name:'显示设备工具栏'}).click();
  await page.getByLabel('视口尺寸预设').selectOption('phone');await page.waitForFunction(()=>document.querySelector('[aria-label="视口宽度"]').value==='390');
  await page.getByRole('button',{name:'旋转视口'}).click();await page.waitForFunction(()=>document.querySelector('[aria-label="视口宽度"]').value==='844');assert.equal(await page.getByLabel('视口高度').inputValue(),'390');
  await page.getByRole('button',{name:'重置',exact:true}).click();await page.waitForFunction(()=>document.querySelector('[aria-label="视口宽度"]').value==='1280');
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  const updates=await page.evaluate(()=>window.updates);await options.click();await page.getByRole('menuitem',{name:'截取屏幕截图'}).click();
  const dialog=page.getByRole('dialog',{name:'截图预览'});await dialog.waitFor();assert.equal(await dialog.getByRole('link',{name:'下载',exact:true}).getAttribute('download'),'computer-use-screenshot.png');
  await dialog.press('Escape');await dialog.waitFor({state:'hidden'});assert.equal(await page.evaluate(()=>window.updates),updates,'taking a screenshot does not update control state');
  await options.click();await page.getByRole('menuitem',{name:'在页面中查找'}).click();
  const find=page.getByRole('searchbox',{name:'查找文字'});await find.fill('中文');await page.getByRole('search').getByText('已找到',{exact:true}).waitFor();
  await find.press('Shift+Enter');await page.getByRole('search').getByText('已回到起点',{exact:true}).waitFor();
  assert.equal(await page.evaluate(()=>window.calls.at(-1).backward),true);
  await find.fill('missing');await page.getByRole('search').getByText('未找到',{exact:true}).waitFor();
  await find.press('Escape');await page.getByRole('search').waitFor({state:'hidden'});assert.equal(await options.evaluate(el=>el===document.activeElement),true);
  const calls=await page.evaluate(()=>window.calls.length);await options.click();await page.getByRole('menuitem',{name:'在页面中查找'}).click();await page.evaluate(()=>new Promise(resolve=>setTimeout(resolve,250)));assert.equal(await page.evaluate(()=>window.calls.length),calls,'reopening find alone does not repeat a control action');await find.press('Escape');
  await page.evaluate(()=>window.switchTab());await options.click();assert.equal(await page.getByRole('menuitem',{name:'截取屏幕截图'}).isEnabled(),false,'cannot capture a stale tab frame');
  assert.equal(await page.evaluate(()=>window.error??''),'');
});
