import test from 'node:test';
import assert from 'node:assert/strict';
import {join} from 'node:path';
import {homedir} from 'node:os';
import {keyboardFixture} from './fixtures/computer-use/keyboard.mjs';
import {ComputerUseManager} from '../src/computer-use/manager.mjs';
const socket=process.env.TRISOUL_CU_NATIVE_SOCKET;
test('native setValue confirms settled values and interrupts a batch when the editor reverts',{skip:process.platform!=='darwin'||!socket,timeout:25000},async t=>{
  const fixture=await keyboardFixture(),manager=new ComputerUseManager(join(fixture.root,'host'),{native:{socket,binary:process.env.TRISOUL_CU_NATIVE_BINARY??join(homedir(),'Applications/Trisoul Computer Use.app/Contents/MacOS/trisoul-computer-use')}});
  t.after(async()=>{await manager.close();await fixture.close();});
  const run=code=>manager.execute('set-value',code);
  assert.equal((await run(`const app=await cua.getApp(${JSON.stringify(fixture.bundle)});const ax=await app.getAXState({emit:false,disableDiffing:true});const editor=Number(ax.match(/\\[(\\d+)\\] AXTextArea 编辑区/)[1]);`)).error,undefined);
  const before=await fixture.command('sample');
  assert.equal((await run("await app.setValue(editor,'正常中文 🌿');")).error,undefined);
  assert.equal((await fixture.command('sample')).text,'正常中文 🌿');
  await fixture.command('revert-ax',{enabled:true});
  const rejected=await run("await app.setValue(editor,'将被编辑器清空');await app.pressKey('super+s');");
  assert.ok(rejected.error,'a silent delayed reset must fail the tool call');
  assert.match(JSON.stringify(rejected.error),/The input did not retain the requested value/);
  const after=await fixture.command('sample');assert.equal(after.text,'');assert.equal(after.action,'');
  assert.equal(after.frontmostPid,before.frontmostPid);assert.deepEqual(after.mouse,before.mouse);
  await fixture.command('revert-ax',{enabled:false});
  assert.equal((await run("await app.setValue(editor,'恢复后可再次输入');")).error,undefined);
  assert.equal((await fixture.command('sample')).text,'恢复后可再次输入');
});
