import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,writeFile}from'node:fs/promises';
import{tmpdir}from'node:os';import{join}from'node:path';
import{chromium}from'playwright';
import sharp from 'sharp';
import{ComputerUseManager}from'../src/computer-use/manager.mjs';
import{startFixture}from'./fixtures/computer-use/server.mjs';
import{extensionFixture}from'./fixtures/computer-use/extension.mjs';

for(const backend of ['managed','extension'])test(backend+': annotation captures matching DOM and pixels without changing model control',{timeout:30000},async t=>{
  const root=await mkdtemp(join(tmpdir(),'trisoul-cu-dom-annotation-')),fixture=await startFixture();
  const external=backend==='extension'?await extensionFixture(t,{fixture}):null;
  const launcher=join(root,'browser'),quote=s=>"'"+s.replaceAll("'","'\\''")+"'";
  if(process.platform==='darwin')await writeFile(launcher,'#!/bin/sh\nexec '+quote(chromium.executablePath())+' --use-mock-keychain "$@"\n',{mode:0o700});
  const manager=new ComputerUseManager(root,{...(external?{extensionHub:external.hub}:{}),browser:process.platform==='darwin'?{executablePath:launcher}:{},native:{binary:join(root,'missing')}});
  t.after(async()=>{await manager.close();await fixture.close();await rm(root,{recursive:true,force:true});});
  const tab=await manager.dispatch('annotation-test','createBrowserTab',[external?.browser.id??'browser',fixture.url]);
  let frame,actor;const close=await manager.watchBrowser('annotation-test',tab.id,(event,value)=>{if(event==='frame')frame=value;if(event==='ready')actor=value.actor;});t.after(close);
  for(let i=0;i<100&&!frame;i++)await new Promise(r=>setTimeout(r,20));assert.ok(frame);
  const views=manager.viewsFor(manager.status('annotation-test').target),view=views.views.get(tab.id),page=view.record.page;
  await page.evaluate(()=>{document.body.insertAdjacentHTML('beforeend','<div id="shadow-host" style="position:fixed;right:20px;top:20px"></div><div style="position:fixed;right:20px;top:100px;width:100px;height:30px;overflow:hidden"><button id="clipped-button" style="margin-top:60px">Hidden by scrollport</button></div>');document.querySelector('#shadow-host').attachShadow({mode:'open'}).innerHTML='<button id="shadow-button">Shadow selection</button>';});
  const before=manager.status('annotation-test'),input=()=>({actor,tabId:tab.id,controlEpoch:manager.status('annotation-test').controlEpoch});
  const capture=()=>manager.annotationSnapshot('annotation-test',input());
  const result=await capture();
  assert.equal(result.frame.mediaType,'image/png');assert.equal(Buffer.from(result.frame.data,'base64').subarray(0,8).toString('hex'),'89504e470d0a1a0a');
  const name=result.elements.find(e=>e.id==='name');assert.ok(name);assert.equal(name.tag,'input');assert.ok(name.styles['font-size']);
  assert.ok(result.elements.some(e=>e.id==='shadow-button'&&e.text==='Shadow selection'),'include visible shadow DOM elements');
  assert.equal(result.elements.some(e=>e.id==='clipped-button'),false,'exclude descendants outside a scrollport');
  const box=await page.locator('#name').boundingBox(),g=result.frame.geometry;
  assert.ok(Math.abs(name.region.x*g.width-box.x)<1&&Math.abs(name.region.width*g.width-box.width)<1,'DOM geometry matches the captured viewport');
  assert.equal(manager.status('annotation-test').controlEpoch,before.controlEpoch);assert.equal(manager.status('annotation-test').status,before.status);
  assert.equal(await page.locator('#name').inputValue(),'');assert.deepEqual(await page.evaluate(()=>fixtureEvents),[]);
  const originalStyle=await page.locator('#name').getAttribute('style');
  const styled=await manager.annotationStylePreview('annotation-test',{...input(),sourceFrameId:result.frame.id,elementKey:name.key,changes:{'background-color':'rgb(20, 100, 200)',width:'300px'}});
  assert.equal(styled.restored.restored,true);assert.equal(styled.element.styles['background-color'],'rgb(20, 100, 200)');
  assert.ok(styled.element.region.width>name.region.width,'preview renders the requested width');
  const previewImage=sharp(Buffer.from(styled.frame.data,'base64')),size=await previewImage.metadata(),region=styled.element.region;
  const pixel=await previewImage.extract({left:Math.floor((region.x+region.width*.75)*size.width),top:Math.floor((region.y+region.height*.5)*size.height),width:1,height:1}).removeAlpha().raw().toBuffer();assert.deepEqual([...pixel],[20,100,200],'returned PNG contains the actual requested background color');
  assert.equal(await page.locator('#name').getAttribute('style'),originalStyle,'successful preview restores the exact original attribute');
  assert.equal(view.stylePreview,null);assert.equal(manager.status('annotation-test').status,'stopped');
  await assert.rejects(manager.annotationStylePreview('annotation-test',{...input(),sourceFrameId:result.frame.id,elementKey:name.key,changes:{color:'not-a-color'}}),/无效的 CSS/);
  assert.equal(await page.locator('#name').getAttribute('style'),originalStyle);
  const styleInput=()=>({...input(),sourceFrameId:result.frame.id,elementKey:name.key,changes:{color:'rgb(10, 20, 30)',width:'290px'}});
  const captureBeforeFailure=views.browser.observeScreenshot;
  views.browser.observeScreenshot=async()=>{await page.locator('#name').evaluate(el=>{el.style.setProperty('outline-width','7px');el.style.setProperty('color','rgb(70, 80, 90)');});throw new Error('injected capture failure');};
  await assert.rejects(manager.annotationStylePreview('annotation-test',styleInput()),/injected capture failure/);
  assert.equal(await page.locator('#name').evaluate(el=>el.style.width),'');assert.equal(await page.locator('#name').evaluate(el=>el.style.color),'rgb(70, 80, 90)','preserve page-owned changes to a previewed property');
  assert.equal(await page.locator('#name').evaluate(el=>el.style.outlineWidth),'7px','preserve unrelated page-owned changes');
  await page.locator('#name').evaluate(el=>el.removeAttribute('style'));views.browser.observeScreenshot=captureBeforeFailure;
  let applied;const applying=new Promise(resolve=>{applied=resolve;});views.browser.observeScreenshot=()=>{applied();return new Promise(()=>{});};
  const cancellation=new AbortController(),cancelled=manager.annotationStylePreview('annotation-test',styleInput(),cancellation.signal);await applying;cancellation.abort();await assert.rejects(cancelled,/abort/i);
  assert.equal(await page.locator('#name').getAttribute('style'),originalStyle,'cancel restores before acknowledging completion');views.browser.observeScreenshot=captureBeforeFailure;
  const send=view.cdp.send.bind(view.cdp);let failRestore=true;
  view.cdp.send=(method,params)=>method==='Runtime.callFunctionOn'&&params.functionDeclaration.includes('return this.restore()')&&failRestore?Promise.reject(new Error('injected restore failure')):send(method,params);
  await assert.rejects(manager.annotationStylePreview('annotation-test',styleInput()),/injected restore failure/);assert.ok(view.stylePreview);
  await assert.rejects(manager.resume('annotation-test'),/Stopping|恢复/);
  await assert.rejects(manager.stop('annotation-test'),/injected restore failure/);assert.ok(view.stylePreview,'failed cleanup keeps the transaction available for retry');
  if(backend==='extension'){await new Promise(resolve=>setTimeout(resolve,5100));assert.equal(await page.locator('#name').getAttribute('style'),originalStyle,'renderer lease also restores if transport confirmation is lost');}
  failRestore=false;await manager.stop('annotation-test');assert.equal(view.stylePreview,null);assert.equal(await page.locator('#name').getAttribute('style'),originalStyle);view.cdp.send=send;
  await view.cdp.send('Emulation.setPageScaleFactor',{pageScaleFactor:1.5});
  const zoomed=await capture(),zoomName=zoomed.elements.find(e=>e.id==='name'),zoomBox=await page.locator('#name').boundingBox();
  assert.equal(zoomed.frame.geometry.scale,1.5);assert.ok(zoomName);
  assert.ok(Math.abs(zoomName.region.x*zoomed.frame.geometry.width-(zoomBox.x-zoomed.frame.geometry.offsetX))<1,'element selection tracks pinch-zoom geometry');
  await view.cdp.send('Emulation.setPageScaleFactor',{pageScaleFactor:1});
  await assert.rejects(manager.annotationSnapshot('annotation-test',{...input(),actor:'stale'}),/已改变/);
  // Navigation during capture must reject, not pair the old DOM with new pixels.
  const original=views.browser.observeScreenshot;let navigated=false;
  views.browser.observeScreenshot=async(...args)=>{if(!navigated){navigated=true;await page.goto(fixture.url+'/changed');}return original.apply(views.browser,args);};
  await assert.rejects(capture(),/changed|改变|变化/i);views.browser.observeScreenshot=original;
  let entered;const started=new Promise(resolve=>{entered=resolve;});views.browser.observeScreenshot=()=>{entered();return new Promise(()=>{});};
  const pending=capture();await started;const rejected=assert.rejects(pending,/closed|关闭|改变/i);await manager.setEnabled(false);await rejected;views.browser.observeScreenshot=original;
  await assert.rejects(capture(),/已关闭/);await close();await manager.setEnabled(true);await assert.rejects(capture(),/已改变|断开/);
});
