import test from 'node:test';
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {mkdtemp,mkdir,readFile,writeFile} from 'node:fs/promises';
import {tmpdir,homedir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {setTimeout as delay} from 'node:timers/promises';
import sharp from 'sharp';
import {ComputerUseManager} from '../src/computer-use/manager.mjs';

const socket=process.env.TRISOUL_CU_NATIVE_SOCKET;
test('native live view: actual frames stay independent of model references and stopping', {skip:process.platform!=='darwin'||!socket,timeout:30000},async t=>{
  const root=await mkdtemp(join(tmpdir(),'trisoul-cu-native-view-')),app=join(root,'Fixture.app'),report=join(root,'truth.json'),command=join(root,'command.json'),bundle='ai.trisoul.nativeview.'+process.pid;
  const manager=new ComputerUseManager(join(root,'host'),{native:{socket,binary:process.env.TRISOUL_CU_NATIVE_BINARY??join(homedir(),'Applications/Trisoul Computer Use.app/Contents/MacOS/trisoul-computer-use')}});
  const wait=async(fn,ms=6000)=>{const deadline=performance.now()+ms;while(performance.now()<deadline){const value=await fn();if(value)return value;await delay(20);}throw Error('Native preview state did not arrive');};
  let pid,close,secondClose;const frames=[],events=[];
  t.after(async()=>{await secondClose?.();await close?.();await manager.close();if(pid)try{process.kill(pid,'SIGTERM');}catch{}console.log('Native live view artifacts:',root);});
  await mkdir(join(app,'Contents/MacOS'),{recursive:true});execFileSync('clang',['-fobjc-arc','-framework','Cocoa',new URL('./fixtures/computer-use/NativeFixture.m',import.meta.url).pathname,'-o',join(app,'Contents/MacOS/Fixture')]);
  await writeFile(join(app,'Contents/Info.plist'),`<?xml version="1.0"?><plist version="1.0"><dict><key>CFBundleIdentifier</key><string>${bundle}</string><key>CFBundleName</key><string>Trisoul Preview Fixture</string><key>CFBundleExecutable</key><string>Fixture</string><key>CFBundlePackageType</key><string>APPL</string></dict></plist>`);
  execFileSync('open',['-n','-g',app,'--args','--report',report,'--command',command]);await wait(async()=>{try{pid=JSON.parse(await readFile(report,'utf8')).pid;return pid;}catch{}});
  const cmd=async(action,args={})=>{const id=randomUUID();await writeFile(command,JSON.stringify({id,action,...args}));await wait(async()=>JSON.parse(await readFile(report,'utf8')).commandId===id);};
  const execute=async code=>{const result=await manager.execute('view',code);assert.equal(result.error,undefined,JSON.stringify(result.error));return result;};
  await execute(`const app=await cua.getApp(${JSON.stringify(bundle)});`);
  await execute(String.raw`const state=await app.getAXState({emit:false,disableDiffing:true});const field=Number(state.match(/\[(\d+)\] AXTextField 姓名/)[1]);const save=Number(state.match(/\[(\d+)\] AXButton Save actions/)[1]);await app.getScreenshot();`);
  const target=manager.status('view').target,modelImage=manager.preview.get('view'),controller=new AbortController();
  close=await manager.watchNative('view',target.id,(type,value)=>{events.push({type,...(type==='frame'?{id:value.id,sequence:value.sequence}:value)});if(type==='frame')frames.push(value);},controller.signal);
  try{await wait(()=>frames[0]);}catch(error){console.log('Preview events:',events);throw error;}
  const first=frames.at(-1);await writeFile(join(root,'first.jpg'),Buffer.from(first.data,'base64'));
  const image=await sharp(Buffer.from(first.data,'base64')).metadata();assert.equal(image.width,first.pixelWidth);assert.equal(image.height,first.pixelHeight);assert.equal(first.width,660);assert.equal(first.height,458);assert.equal(first.geometryVerified,true);
  await execute("await app.setValue(field,'实时画面保持引用');await app.click(save);");
  assert.equal(JSON.parse(await readFile(report,'utf8')).result,'Save | 实时画面保持引用');
  await wait(()=>frames.at(-1)?.data!==first.data);assert.equal(manager.preview.get('view'),modelImage,'preview frames never become model screenshot attachments');
  await writeFile(join(root,'window-inventory.json'),JSON.stringify(await manager.native.windows('view-inspector',pid),null,2));
  await execute(`const same=await cua.getApp(${JSON.stringify(bundle)});nodeRepl.write(same.id);`);assert.equal(manager.status('view').target.id,target.id,'the capture indicator is not a second document window');
  await execute('await app.click([258,211]);');await wait(()=>events.some(event=>event.type==='cursor'&&event.source));
  const previousCapture=manager.nativeViews.views.get(target.viewId).sessionId,call=manager.native.call.bind(manager.native);let interrupted=false;
  manager.native.call=async(...args)=>{const result=await call(...args);if(args[0]===previousCapture&&args[1]==='preview_frame'&&!interrupted){interrupted=true;throw Object.assign(new Error('injected ScreenCaptureKit connection interruption'),{code:'CAPTURE_INTERRUPTED'});}return result;};
  const previousFrame=frames.at(-1).id;await wait(()=>interrupted&&frames.at(-1).id!==previousFrame&&manager.nativeViews.views.get(target.viewId)?.sessionId!==previousCapture);
  assert.equal(manager.native.connections.has(previousCapture),false,'the interrupted recording is released before replacement');assert.equal(manager.nativeViews.views.get(target.viewId).restarts,1);manager.native.call=call;
  const sharedSession=manager.nativeViews.views.get(target.viewId).sessionId,secondFrames=[];
  secondClose=await manager.watchNative('view',target.viewId,(type,value)=>{if(type==='frame')secondFrames.push(value);},new AbortController().signal);
  assert.equal(manager.nativeViews.views.size,1);assert.equal(manager.nativeViews.views.get(target.viewId).sessionId,sharedSession);
  await close();close=null;const secondBefore=secondFrames.at(-1).data;
  await cmd('text',{value:'第二个面板继续查看'});await wait(()=>secondFrames.at(-1)?.data!==secondBefore);
  await secondClose();secondClose=null;assert.equal(manager.nativeViews.views.size,0);
  close=await manager.watchNative('view',target.viewId,(type,value)=>{if(type==='frame')frames.push(value);},new AbortController().signal);
  await manager.stop('view');const count=frames.length;
  // A local user action remains observable after the assistant releases input.
  await cmd('text',{value:'停止后继续查看'});await wait(()=>frames.length>count);
  await close();close=null;const ended=frames.length;await delay(200);assert.equal(frames.length,ended);assert.equal(manager.nativeViews.views.size,0);
  // Reopening the pane uses the retained window identity after model release.
  close=await manager.watchNative('view',target.viewId,(type,value)=>{if(type==='frame')frames.push(value);},new AbortController().signal);
  await wait(()=>frames.length>ended);
  await cmd('resize',{width:840,height:520});await wait(()=>frames.at(-1)?.width===840&&frames.at(-1)?.height===548);
  await writeFile(join(root,'resized.jpg'),Buffer.from(frames.at(-1).data,'base64'));
  await cmd('move',{x:230,y:190});await wait(()=>frames.at(-1)?.bounds.x===230);
  const moved=(await manager.native.windows('view-inspector',pid)).find(window=>window.window_id===manager.session('view').nativeTarget.windowId);
  assert.deepEqual(frames.at(-1).bounds,moved.bounds,'the frame records the moved window geometry');
  const capture=manager.nativeViews.views.get(target.viewId).sessionId;
  await manager.resume('view');await execute(`const rebound=await cua.getApp(${JSON.stringify(bundle)});`);
  assert.notEqual(manager.status('view').target.id,target.id,'model authority is renewed');assert.equal(manager.status('view').target.viewId,target.viewId,'the physical window view stays stable');
  assert.equal(manager.nativeViews.views.get(target.viewId).sessionId,capture,'rebinding does not restart recording');
  await manager.setEnabled(false);assert.equal(manager.nativeViews.views.size,0);await assert.rejects(manager.watchNative('view',target.id,()=>{},new AbortController().signal),/已关闭/);
  assert.doesNotThrow(()=>process.kill(pid,0),'closing capture preserves the user application');
  await close();close=null;await manager.setEnabled(true);await manager.resume('view');await execute(`const reopened=await cua.getApp(${JSON.stringify(bundle)});`);
  for(const jitter of [0,2,10,20]){
    const abort=new AbortController();const pending=manager.watchNative('view',target.viewId,()=>{},abort.signal);const checked=pending.then(value=>({close:value}),error=>({error}));
    await delay(jitter);abort.abort(new Error('fixture closes the pane during startup'));const result=await checked;await result.close?.();
    await wait(()=>manager.nativeViews.views.size===0);assert.equal([...manager.native.connections.keys()].filter(id=>id.startsWith('native-preview-')).length,0);
  }
  const closedEvents=[];close=await manager.watchNative('view',target.viewId,(type,value)=>closedEvents.push({type,value}),new AbortController().signal);
  await wait(()=>closedEvents.some(event=>event.type==='frame'));
  const disconnected=manager.nativeViews.views.get(target.viewId),transport=await manager.native.connections.get(disconnected.sessionId);
  transport.client.child.kill('SIGKILL');await wait(()=>closedEvents.some(event=>event.type==='failure'));await wait(()=>manager.nativeViews.views.size===0);
  assert.equal(manager.native.connections.has(disconnected.sessionId),false,'a disconnected preview is removed only after native cleanup confirmation');await close();close=null;
  closedEvents.length=0;close=await manager.watchNative('view',target.viewId,(type,value)=>closedEvents.push({type,value}),new AbortController().signal);
  await wait(()=>closedEvents.some(event=>event.type==='frame'));await cmd('close');
  try{await wait(()=>closedEvents.some(event=>event.type==='closed'));}catch(error){console.log('Close events:',closedEvents.filter(event=>event.type!=='frame'));console.log('Closed window inventory:',await manager.native.windows('view-inspector',pid));throw error;}await wait(()=>manager.nativeViews.views.size===0);
  assert.equal(manager.status('view').target,null);assert.doesNotThrow(()=>process.kill(pid,0),'closing a document preserves its application process');
});
