import test from 'node:test';
import assert from 'node:assert/strict';
import { writeFile, readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { ExtensionBrowser } from '../src/computer-use/extension-browser.mjs';
import { BrowserViews } from '../src/computer-use/browser-view.mjs';
import { extensionFixture } from './fixtures/computer-use/extension.mjs';
import { ExtensionHub } from '../src/computer-use/extension-hub.mjs';

test('Windows: installed exe connects real Chrome, preserves selected tabs and unregisters its own host', { skip: process.platform !== 'win32', timeout: 240000 }, async t => {
  const env = await extensionFixture(t, { install: true, prefix: "omd-win-browser 中文 '-" });
  const host = new ExtensionBrowser(env.hub, env.browser), views = new BrowserViews(host);
  const page = await env.context.newPage(); await page.goto(env.fixture.url);
  const unrelated = await env.context.newPage(); await unrelated.goto(env.fixture.url + '/unrelated');
  try {
    const installed = await env.installer.status(env.hub.list());
    assert.equal(installed.prepared, true); assert.equal(installed.reloadRequired, false);
    assert.equal(installed.build, env.browser.build);
    const registration = await env.installer.windows.read(env.installer.hostName);
    assert.ok(registration.every(entry => entry.value?.toLowerCase() === env.installer.registration.toLowerCase()), JSON.stringify({ expected: env.installer.registration, registration }));
    const duplicate = new ExtensionHub(env.hub.socketPath, { windowsRuntime: env.installer.windows });
    await assert.rejects(duplicate.start(), /exited/); await duplicate.close();
    assert.equal(env.hub.list().length, 1, 'failed endpoint takeover leaves the original connection intact');
    const tab = (await host.list('windows-test')).find(tab => tab.url === env.fixture.url + '/');
    await host.target('windows-test', tab.id);
    await assert.rejects(host.target('other-session', tab.id), /another conversation/);
    const observed = await host.invoke('windows-test', tab.id, 'getAXStateAndScreenshot');
    assert.equal(Buffer.from(observed.screenshot, 'base64').readUInt32BE(0), 0x89504e47);
    const id = Number(observed.state.match(/(\d+) textbox "姓名"/)[1]);
    await host.invoke('windows-test', tab.id, 'setValue', [id, 'Windows 中文 🧭']);
    assert.equal(await page.getByLabel('姓名', { exact: true }).inputValue(), 'Windows 中文 🧭');
    const record = await host.target('windows-test', tab.id);
    await record.page.getByRole('button', { name: '保存', exact: true }).click();
    assert.equal(await page.evaluate(() => fixtureEvents.at(-1).value.name), 'Windows 中文 🧭');
    let frame;
    const unsubscribe = await views.subscribe(tab.id, (event, data) => { if (event === 'frame') frame = data; });
    for (let i = 0; i < 200 && !frame; i++) await new Promise(resolve => setTimeout(resolve, 25));
    assert.ok(frame?.data, 'real Windows browser pixels arrive through the installed pipe helper');
    await record.page.mouse.move(100, 100); await record.page.mouse.down();
    assert.equal(await page.evaluate(() => fixtureMouseHeld), true);
    await host.disconnect('windows-test');
    assert.equal(await page.evaluate(() => fixtureMouseHeld), false);
    assert.equal(page.isClosed(), false); assert.equal(unrelated.isClosed(), false);
    assert.equal(views.views.get(tab.id).record.page.isClosed(), false);
    const rebound = await host.target('windows-test', tab.id);
    await rebound.page.goto(env.fixture.url + '/cross-frames');
    const nested = await host.invoke('windows-test', tab.id, 'getAXState');
    const inner = Number(nested.state.match(/(\d+) textbox "框架输入"/)[1]);
    await host.invoke('windows-test', tab.id, 'setValue', [inner, 'Windows 跨源框架']);
    assert.equal(await page.frameLocator('iframe').frameLocator('iframe').getByLabel('框架输入').inputValue(), 'Windows 跨源框架');
    await unsubscribe(); await views.close(); await host.close();
    // Disk repair is separate from the version actually loaded by Chrome.
    const popup = join(env.installer.extensionPath, 'popup.js'), original = await readFile(popup);
    await writeFile(popup, 'damaged Windows fixture'); assert.equal((await env.installer.status()).prepared, false);
    await env.installer.prepare(); assert.deepEqual(await readFile(popup), original);
    await env.hub.close(); await env.installer.unregister();
    assert.ok((await env.installer.windows.read(env.installer.hostName)).every(entry => !entry.hasValue));
    assert.equal((await env.installer.status()).prepared, false);
    assert.equal(page.isClosed(), false); assert.equal(unrelated.isClosed(), false);
  } finally { await views.close(); await host.close(); }
});
