import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {setTimeout as delay} from 'node:timers/promises';
import {chromium} from 'playwright';
import {ComputerUseManager} from '../src/computer-use/manager.mjs';
import {startFixture} from './fixtures/computer-use/server.mjs';
import {extensionFixture} from './fixtures/computer-use/extension.mjs';
const until=async fn=>{for(let i=0;i<250;i++){if(await fn())return;await delay(20);}throw Error('independent view timed out');};

for(const backend of ['managed','extension'])test(backend+': viewing a different tab preserves active execution; input stops and adopts the viewed tab',{timeout:30000},async t=>{
  const root=await mkdtemp(join(tmpdir(),'trisoul-independent-view-')),fixture=await startFixture();
  // Use the actual Chrome window viewport. A second Playwright metrics
  // override would make reset restore the window rather than that fixture.
  const external=backend==='extension'?await extensionFixture(t,{fixture,viewport:null}):null;
  const launcher=join(root,'browser'),quote=s=>"'"+s.replaceAll("'","'\\''")+"'";
  if(process.platform==='darwin')await writeFile(launcher,'#!/bin/sh\nexec '+quote(chromium.executablePath())+' --use-mock-keychain "$@"\n',{mode:0o700});
  const opened=[],manager=new ComputerUseManager(root,{...(external?{extensionHub:external.hub}:{}),browser:process.platform==='darwin'?{executablePath:launcher}:{},native:{binary:join(root,'missing')},openExternal:async url=>opened.push(url)});
  t.after(async()=>{await manager.close();await fixture.close();await rm(root,{recursive:true,force:true});});
  const id='view',browserId=external?.browser.id??'browser';
  const a=await manager.dispatch(id,'createBrowserTab',[browserId,fixture.url]),b=await manager.dispatch(id,'createBrowserTab',[browserId,fixture.url+'/second']);
  const working=manager.execute(id,'await new Promise(r=>setTimeout(r,15000)); nodeRepl.write("completed");').catch(error=>({error}));
  await until(()=>manager.status(id).status==='running');
  const before=manager.status(id),connection=manager.browserForTab(b.id).connections.get(id);
  await manager.viewTab(id,{tabId:a.id,browserId});
  const viewed=manager.status(id);
  assert.equal(viewed.target.id,b.id);assert.equal(viewed.viewTarget.id,a.id);assert.equal(viewed.status,'running');assert.equal(viewed.controlEpoch,before.controlEpoch);
  assert.equal(manager.browserForTab(b.id).connections.get(id),connection,'viewing cannot disconnect the model channel');
  await manager.openViewedExternally(id,{tabId:a.id,expectedUrl:fixture.url});assert.deepEqual(opened,[new URL(fixture.url).href]);assert.equal(manager.status(id).status,'running');assert.equal(manager.status(id).controlEpoch,before.controlEpoch);
  await assert.rejects(manager.viewTab('foreign',{tabId:a.id,browserId}),/其他对话/);
  let frame,actor,closed=false;
  const close=await manager.watchBrowser(id,a.id,(event,value)=>{if(event==='frame')frame=value;if(event==='ready')actor=value.actor;if(event==='closed')closed=true;},undefined,false,true);t.after(close);
  await until(()=>frame);
  const layoutInput={actor,tabId:a.id,controlEpoch:before.controlEpoch,size:{width:640,height:600}};
  await assert.rejects(manager.layoutViewedTab('foreign',layoutInput),/网页已改变/);
  assert.equal(manager.status(id).viewViewport.layoutSupported,backend==='managed');
  const layout=await manager.layoutViewedTab(id,layoutInput);
  assert.equal(layout.layout,backend==='managed'?'applied':'fixed');
  if(backend==='managed'){
    await until(()=>frame.width===640&&frame.height===600);
    const page=manager.viewsFor(a).views.get(a.id).record.page;
    assert.deepEqual(await page.evaluate(()=>({width:innerWidth,height:innerHeight})),{width:640,height:600},'layout resizes the actual document instead of stretching a screenshot');
    assert.equal(manager.status(id).viewViewport.overridden,false,'normal layout does not enable device emulation controls');
    manager.session(id).manualBusy=true;
    assert.equal((await manager.layoutViewedTab(id,{...layoutInput,size:{width:500,height:600}})).layout,'deferred','no layout change during manual input');
    manager.session(id).manualBusy=false;
    const abort=new AbortController();abort.abort(new Error('layout cancelled'));
    await assert.rejects(manager.layoutViewedTab(id,{...layoutInput,size:{width:500,height:600}},abort.signal),/cancelled/);
    assert.deepEqual(await page.evaluate(()=>({width:innerWidth,height:innerHeight})),{width:640,height:600});
  }
  assert.equal(manager.status(id).status,'running');assert.equal(manager.status(id).controlEpoch,before.controlEpoch);
  assert.equal(manager.status(id).target.id,b.id,'layout cannot adopt the viewed tab');
  assert.equal(manager.browserForTab(b.id).connections.get(id),connection,'layout keeps the active model channel');
  const capture=await manager.annotationSnapshot(id,{actor,tabId:a.id,controlEpoch:before.controlEpoch});
  const screenshot=await manager.viewScreenshot(id,{actor,tabId:a.id,controlEpoch:before.controlEpoch});
  assert.equal(Buffer.from(screenshot.data,'base64').subarray(0,8).toString('hex'),'89504e470d0a1a0a');
  assert.ok(capture.elements.find(e=>e.id==='name'));assert.equal(manager.status(id).target.id,b.id);assert.equal(manager.status(id).status,'running');assert.equal(closed,false);
  const page=manager.viewsFor(a).views.get(a.id).record.page,box=await page.getByLabel('姓名',{exact:true}).boundingBox();
  const input=type=>({type,actor,tabId:a.id,frameId:frame.id,controlEpoch:manager.status(id).controlEpoch,x:(box.x+box.width/2)/frame.width,y:(box.y+box.height/2)/frame.height});
  await manager.manualInput(id,input('pointerdown'));await manager.manualInput(id,input('pointerup'));
  assert.equal(manager.status(id).target.id,a.id);assert.equal(manager.status(id).status,'stopped');
  assert.ok((await working).error,'the explicit input cancels execution');
  await manager.manualInput(id,{...input('text'),text:'独立查看后接管'});
  assert.equal(await page.getByLabel('姓名',{exact:true}).inputValue(),'独立查看后接管');
  await manager.viewTab(id,{tabId:b.id,browserId});
  assert.equal([...manager.session(id).userTabs].at(-1),b.id,'viewing updates the recent-tab order used after closing a tab');
  await assert.rejects(manager.manualInput(id,input('pointerdown')),/画面已断开|目标已改变/);
  assert.equal(manager.status(id).target.id,a.id,'a second view change is still not control');
  await manager.viewTab(id,{current:true});assert.equal(manager.status(id).viewTarget.id,a.id);
  await manager.viewTab(id,{tabId:b.id,browserId});
  let frameB,actorB;const closeB=await manager.watchBrowser(id,b.id,(event,value)=>{if(event==='frame')frameB=value;if(event==='ready')actorB=value.actor;},undefined,false,true);t.after(closeB);await until(()=>frameB);
  const pageB=manager.viewsFor(b).views.get(b.id).record.page,original=await pageB.evaluate(()=>({width:innerWidth,height:innerHeight}));
  const viewportInput=()=>({actor:actorB,tabId:b.id,controlEpoch:manager.status(id).controlEpoch});
  const trace=label=>{if(process.env.TRISOUL_VIEW_TRACE)console.log(backend,label);};trace('before resize');
  const beforeResize=manager.status(id);await assert.rejects(manager.resizeViewedTab(id,{...viewportInput(),size:{width:0,height:844}}),/positive integers/);assert.equal(manager.status(id).controlEpoch,beforeResize.controlEpoch);
  await manager.resizeViewedTab(id,{...viewportInput(),size:{width:390,height:844}});
  await until(()=>frameB.width===390&&frameB.height===844).catch(async error=>{console.log('Viewport diagnostic',JSON.stringify({frame:{width:frameB.width,height:frameB.height,geometry:frameB.geometry},actual:await pageB.evaluate(()=>({width:innerWidth,height:innerHeight})),viewClosed:manager.viewsFor(b).views.get(b.id)?.closed}));throw error;});
  assert.deepEqual(await pageB.evaluate(()=>({width:innerWidth,height:innerHeight})),{width:390,height:844});assert.equal(manager.status(id).viewViewport.overridden,true);
  const browser=manager.viewsFor(b).browser,resize=browser.setViewport.bind(browser);let releaseResize;
  trace('before cancellation');
  browser.setViewport=async(record,size)=>{await resize(record,size);if(size.width===420)await new Promise(resolve=>{releaseResize=resolve;});};
  const controller=new AbortController(),cancelled=manager.resizeViewedTab(id,{...viewportInput(),size:{width:420,height:600}},controller.signal);
  await until(()=>releaseResize);controller.abort(new Error('fixture cancelled'));releaseResize();await assert.rejects(cancelled,/fixture cancelled/);browser.setViewport=resize;
  trace('cancelled');
  assert.deepEqual(await pageB.evaluate(()=>({width:innerWidth,height:innerHeight})),{width:390,height:844},'cancellation restores the previous device dimensions');
  await manager.navigate(id,{tabId:b.id,url:fixture.url+'/final',controlEpoch:manager.status(id).controlEpoch});
  trace('navigated');
  assert.equal(manager.status(id).target.id,b.id);assert.equal(manager.status(id).viewTarget.url,fixture.url+'/final');
  assert.deepEqual(await pageB.evaluate(()=>({width:innerWidth,height:innerHeight})),{width:390,height:844},'navigation keeps the chosen device dimensions');
  await manager.resizeViewedTab(id,{...viewportInput(),size:null});
  trace('reset');
  await until(async()=>JSON.stringify(await pageB.evaluate(()=>({width:innerWidth,height:innerHeight})))===JSON.stringify(original)).catch(async error=>{console.log('Viewport reset diagnostic',JSON.stringify({original,actual:await pageB.evaluate(()=>({width:innerWidth,height:innerHeight})),frame:{width:frameB.width,height:frameB.height},overridden:manager.status(id).viewViewport.overridden}));throw error;});
  assert.equal(manager.status(id).viewViewport.overridden,false);
  await pageB.setContent('<p id="first">查找<span>演示</span> 第一处</p><p hidden>不可见查找</p><div style="height:1200px"></div><p id="second">查找演示 第二处</p><iframe srcdoc="<p>查找演示 框架</p>"></iframe>');
  await until(()=>pageB.frames().length===2);
  const search=query=>manager.findViewedText(id,{...viewportInput(),query});
  const first=await search('查找演示');assert.equal(first.find.found,true);
  assert.equal(await pageB.evaluate(()=>getSelection().anchorNode.parentElement.closest('p').id),'first');
  await search('查找演示');assert.equal(await pageB.evaluate(()=>getSelection().anchorNode.parentElement.closest('p').id),'second');assert.ok(await pageB.evaluate(()=>scrollY>0));
  await search('查找演示');assert.equal(await pageB.frames()[1].evaluate(()=>getSelection().toString()),'查找演示');
  await manager.findViewedText(id,{...viewportInput(),query:'查找演示',backward:true});assert.equal(await pageB.evaluate(()=>getSelection().anchorNode.parentElement.closest('p').id),'second');
  assert.equal((await search('不可见查找')).find.found,false);
  assert.equal((await search('不存在的文字')).find.found,false);
  await manager.navigate(id,{tabId:b.id,url:fixture.url+'/cross-frames',controlEpoch:manager.status(id).controlEpoch});
  await until(()=>pageB.frames().some(frame=>frame.url().endsWith('/frame')));
  assert.equal((await search('框架按钮')).find.found,true,'search reaches nested cross-origin documents');
  assert.equal(await pageB.frames().find(frame=>frame.url().endsWith('/frame')).evaluate(()=>getSelection().toString()),'框架按钮');
  await assert.rejects(manager.findViewedText('foreign',{...viewportInput(),query:'查找演示'}),/画面已改变/);
  await closeB();await close();
  trace('closed');
});

test('late view selection cannot override a newer selection, and disabled viewing is rejected',async t=>{
  const root=await mkdtemp(join(tmpdir(),'trisoul-view-order-')),manager=new ComputerUseManager(root,{native:{binary:join(root,'missing')}});
  t.after(async()=>{await manager.close();await rm(root,{recursive:true,force:true});});
  const tabs=['a','b'].map(id=>({id,browserId:'browser',kind:'tab',available:true}));
  for(const tab of tabs)manager.browser.records.set(tab.id,tab);
  manager.browser.target=async()=>({});
  const requests=[];manager.listUserTabs=()=>new Promise(resolve=>requests.push(()=>resolve(tabs)));
  const first=manager.viewTab('view',{tabId:'a'}),second=manager.viewTab('view',{tabId:'b'});
  requests[1]();await second;requests[0]();await first;
  assert.equal(manager.status('view').viewTarget.id,'b');assert.equal(manager.status('view').target,null);assert.equal(manager.status('view').controlEpoch,0);
  const pending=manager.viewTab('view',{tabId:'a'});await manager.setEnabled(false);requests[2]();await assert.rejects(pending,/已关闭/);
  assert.equal(manager.status('view').viewTarget.id,'b');
});
