import test from 'node:test';
import assert from 'node:assert/strict';
import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { frontendFixture, until } from './fixtures/frontend.mjs';

test('DSH frontend: one workbench, preserved edits, compact composer and both themes', { timeout: 90000 }, async t => {
  const f = await frontendFixture(t), { page, root, errors } = f;
  assert.equal(await page.locator('.tx-wordmark').innerText(), 'Oh My DSH');
  await until(async () => (await page.title()).endsWith(' — Oh My DSH'));
  assert.match(await page.title(), /整理工作台和对话界面/);
  assert.equal(await page.getByText('trisoul_x', { exact: true }).count(), 0);
  const screenshot = async name => { if (process.env.TRISOUL_UI_ARTIFACTS) { await page.mouse.move(1, 1); await page.evaluate(() => Promise.all(document.getAnimations().filter(a => a.effect?.getTiming().iterations !== Infinity).map(a => a.finished.catch(() => {})))); await page.screenshot({ path: join(root, name + '.png') }); } };
  t.after(async () => { if (process.env.TRISOUL_UI_ARTIFACTS) console.log('Frontend UI artifacts:', root); });
  assert.equal(await page.locator('.tx-composer-dock').count(), 1);
  assert.equal(await page.locator('.tx-cu-chip').count(), 1);
  assert.equal(await page.getByRole('button', { name: '分享窗口', exact: true }).count(), 1);
  const composer = page.locator('[data-composer-card]');
  assert.ok((await composer.boundingBox()).height < 160, 'empty composer stays compact');
  await screenshot('conversation-light');
  await page.getByRole('button', { name: '打开工作台', exact: true }).click();
  const workbench = page.locator('.tx-workbench'), nav = workbench.getByRole('navigation', { name: '工作台导航' });
  await until(async () => (await workbench.boundingBox())?.width > 300);
  await page.getByRole('heading', { name: '工作上下文', exact: true }).waitFor();
  const tabCount = await page.getByRole('tab').count();
  for (const name of ['记忆', '电脑', '监控', '任务']) {
    await nav.getByRole('button', { name, exact: true }).click();
    await until(async () => (await nav.getByRole('button', { name, exact: true }).getAttribute('aria-current')) === 'page');
    assert.equal(await page.locator('.tx-workbench').count(), 1, 'navigation reuses the same workbench');
    assert.equal(await page.getByRole('tab').count(), name === '任务' || name === '监控' ? tabCount : tabCount - 3, 'no new dock tab is created');
    await screenshot('workbench-' + name);
  }
  await nav.getByRole('button', { name: '记忆', exact: true }).click();
  await page.getByRole('button', { name: '新增', exact: true }).click();
  const editor = page.locator('.tx-editor');
  await editor.locator('textarea').fill('界面改版使用浅色和深色主题，保留原有能力。');
  await nav.getByRole('button', { name: '电脑', exact: true }).click();
  await nav.getByRole('button', { name: '记忆', exact: true }).click();
  assert.equal(await editor.locator('textarea').inputValue(), '界面改版使用浅色和深色主题，保留原有能力。', 'switching views keeps unsaved memory edits');
  await editor.getByRole('button', { name: '保存记忆', exact: true }).click();
  await page.locator('.tx-memory-text').getByText('界面改版使用浅色和深色主题，保留原有能力。', { exact: true }).waitFor();
  await screenshot('memory-populated');
  await page.getByRole('button', { name: 'BT · Better Todo', exact: true }).click();
  await page.getByText('待办完成提醒', { exact: true }).waitFor();
  await screenshot('todo-menu');
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: '打开 Computer Use', exact: true }).click();
  await page.getByRole('heading', { name: '让助手操作应用和网页', exact: true }).waitFor();
  assert.equal(await page.locator('.tx-workbench').count(), 1);
  await screenshot('computer-empty');
  await page.getByRole('button', { name: '运行环境与权限', exact: true }).click();
  await page.getByText('Chrome 扩展', { exact: true }).waitFor();
  await screenshot('computer-setup');
  const light = await workbench.evaluate(el => getComputedStyle(el).backgroundColor);
  await page.emulateMedia({ colorScheme: 'dark' });
  await until(async () => await workbench.evaluate(el => getComputedStyle(el).backgroundColor) !== light);
  await screenshot('computer-dark');
  await nav.getByRole('button', { name: '记忆', exact: true }).click();
  await screenshot('memory-dark');
  await page.setViewportSize({ width: 1060, height: 900 });
  await until(async () => (await composer.boundingBox())?.width >= 220);
  const panelOverflow = await workbench.evaluate(el => el.scrollWidth > el.clientWidth || [...el.querySelectorAll('.tx-app, .tx-body, .tx-cu-pane')].filter(e => e.getBoundingClientRect().width).some(e => e.scrollWidth > e.clientWidth + 1));
  assert.equal(panelOverflow, false, 'all visible panel controls fit a narrow pane');
  await screenshot('narrow-workbench');
  await page.getByRole('button', { name: '收起右侧边栏', exact: true }).click();
  await workbench.waitFor({state:'hidden'});
  await page.setViewportSize({ width: 760, height: 900 });
  await page.locator('[data-sidebar-collapsed=true]').waitFor();
  await page.mouse.move(700, 400);
  await until(async () => (await composer.boundingBox())?.width > 450);
  const tools = await page.locator('[data-slot="conversation.composer.dock"]').boundingBox();
  assert.ok(tools.x >= 0 && tools.x + tools.width <= 760, 'composer tools remain on screen');
  await screenshot('conversation-narrow-dark');
  await page.getByRole('button', { name: '设置', exact: true }).click();
  const settingsDialog = page.getByRole('dialog');
  await settingsDialog.getByRole('button', { name: 'Oh My DSH', exact: true }).click();
  const settings = page.locator('.tx-settings');
  await settings.getByRole('button', { name: '保存设置', exact: true }).waitFor();
  await screenshot('settings-dark');
  await page.emulateMedia({ colorScheme: 'light' });
  await screenshot('settings-light');
  await settings.getByRole('button', { name: /会话级/ }).click();
  assert.equal(await settings.getByRole('button', { name: '保存设置', exact: true }).isEnabled(), true);
  await settings.getByRole('button', { name: '撤销', exact: true }).click();
  assert.equal(await settings.getByRole('button', { name: '保存设置', exact: true }).isEnabled(), false);
  await settings.getByRole('button', { name: /会话级/ }).click();
  await settings.getByRole('button', { name: '保存设置', exact: true }).click();
  await until(async () => !(await settings.getByRole('button', { name: '保存设置', exact: true }).isEnabled()));
  await settings.getByRole('tab', { name: '高级', exact: true }).click();
  await screenshot('settings-advanced');
  await page.keyboard.press('Escape');
  const release = f.holdNextReply();
  try {
    await f.rpc('session/prompt', { requestId: crypto.randomUUID(), sessionId: f.sessionId, mode: 'queue', content: [{ type: 'text', text: '检查运行图标' }] });
    await page.locator('html[data-omd-running]').waitFor();
    const rotor = page.locator('.tx-brand-mark .omd-whale-rotor').first();
    const transform = await rotor.evaluate(el => getComputedStyle(el).transform);
    await until(async () => await rotor.evaluate(el => getComputedStyle(el).transform) !== transform);
    await page.emulateMedia({ reducedMotion: 'reduce' });
    await until(async () => await rotor.evaluate(el => getComputedStyle(el).animationName) === 'none');
  } finally { release(); }
  await until(async () => !(await page.locator('html').getAttribute('data-omd-running')) && !(await page.locator('html').evaluate(el => el.hasAttribute('data-omd-running'))));
  await page.emulateMedia({ reducedMotion: 'no-preference' });
  if (process.env.TRISOUL_UI_ARTIFACTS) await writeFile(join(root, 'visible-elements.json'), JSON.stringify(await page.locator('[data-chat-flow-key]').evaluateAll(els => els.map(el => ({ attrs: [...el.attributes].map(a => [a.name, a.value]), html: el.innerHTML.slice(-14000) }))), null, 2));
  assert.deepEqual(errors, []);
});
