<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <UseWPF>true</UseWPF>
    <AssemblyName>OhMyDsh.Desktop</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <DebugType>none</DebugType>
    <TrisoulBuild Condition="'$(TrisoulBuild)' == ''">development</TrisoulBuild>
  </PropertyGroup>
  <ItemGroup>
    <AssemblyMetadata Include="TrisoulBuild" Value="$(TrisoulBuild)" />
  </ItemGroup>
</Project>
