import z from '@deepseek-ai/schemastery';
import { FREQUENCY_PRESETS } from './frequency.mjs';

const route = z.object({ provider: z.string().default(''), model: z.string().default(''), temperature: z.number().default(0.7), effort: z.string().default('off') });
const cadence = FREQUENCY_PRESETS.medium;
export const Config = z.object({
  dataDir: z.string(),
  memoryScope: z.union(['full', 'project', 'session']).default('full'),
  backgroundMode: z.union(['unified', 'separate']).default('separate'),
  unifiedBackground: route.default({}),
  background: route.default({}),
  canvas: route.default({}),
  surgeon: route.default({}),
  jobTimeoutMs: z.number().step(1).min(0).default(120000),
  digestEvery: z.number().step(1).min(1).default(cadence.digestEvery),
  digestBatchMax: z.number().step(1).min(0).default(0),
  digestEventChars: z.number().step(1).min(0).default(0),
  digestMaxTokens: z.number().step(1).min(0).default(0),
  catchupMax: z.number().step(1).min(0).default(0),
  contextMemories: z.number().step(1).min(0).default(0),
  flushIdleMs: z.number().step(1).min(0).default(90000),
  injectLimit: z.number().step(1).min(0).default(0),
  injectBatch: z.number().step(1).min(1).default(8),
  injectMaxPerSession: z.number().step(1).min(0).default(4),
  injectPickTimeoutMs: z.number().step(1).min(0).default(8000),
  supplementMinSteps: z.number().step(1).min(0).default(cadence.supplementMinSteps),
  supplementMode: z.union(['renew', 'rewrite', 'append']).default('renew'),
  recallMaxTokens: z.number().step(1).min(0).default(0),
  stateEnabled: z.boolean().default(true),
  stateEvery: z.number().step(1).min(1).default(cadence.stateEvery),
  stateBatchMax: z.number().step(1).min(0).default(0),
  statePinnedMax: z.number().step(1).min(0).default(0),
  stateEventChars: z.number().step(1).min(0).default(0),
  stateMaxTokens: z.number().step(1).min(0).default(0),
  stateFailCooldownSteps: z.number().step(1).min(0).default(3),
  stateFailLimit: z.number().step(1).min(0).default(2),
  curateMinGapMs: z.number().step(1).min(0).default(180000),
  curateEvery: z.number().step(1).min(0).default(0),
  curateLimit: z.number().step(1).min(0).default(0),
  curateMaxTokens: z.number().step(1).min(0).default(0),
  surgeonMaxTokens: z.number().step(1).min(0).default(0),
  curateOpsMax: z.number().step(1).min(0).default(0),
  probeEnabled: z.boolean().default(true),
  probeSourceChars: z.number().step(1).min(0).default(0),
  probeMaxTokens: z.number().step(1).min(0).default(0),
  probePatch: z.union(['ride', 'qa', 'material']).default('ride'),
  probePatchChars: z.number().step(1).min(0).default(0),
  shadowStale: z.number().step(1).min(0).default(0),
  userRetirement: z.boolean().default(false),
  requireShorter: z.boolean().default(true),
  mergeCheckpoints: z.boolean().default(true),
  semanticCompaction: z.boolean().default(true),
  minRegionEvents: z.number().step(1).min(1).default(3),
  minRegionTokens: z.number().step(1).min(1).default(cadence.minRegionTokens),
  keepTailEvents: z.number().step(1).min(2).default(30),
  surgeryCooldownSteps: z.number().step(1).min(0).default(cadence.surgeryCooldownSteps),
  surgeryFailCooldownSteps: z.number().step(1).min(0).default(3),
  thresholdChars: z.number().step(1).min(0).default(0),
  thresholdFallbackChars: z.number().step(1).min(0).default(1000000),
  thresholdRatio: z.number().min(0.1).max(0.95).default(0.5),
});
